---
# Source: hello-kubernetes/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-kubernetes
  labels:
    app.kubernetes.io/name: hello-kubernetes
    app.kubernetes.io/version: "1.10"
---
# Source: hello-kubernetes/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes
  namespace: goodbye
  labels:
    app.kubernetes.io/name: hello-kubernetes
    app.kubernetes.io/version: "1.10"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: hello-kubernetes
---
# Source: hello-kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
  namespace: goodbye
  labels:
    app.kubernetes.io/name: hello-kubernetes
    app.kubernetes.io/version: "1.10"
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-kubernetes
    template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-kubernetes
        spec:
      serviceAccountName: hello-kubernetes
      containers:
        - name: hello-kubernetes
          image: "paulbouwer/hello-kubernetes:1.10"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
          - name: message
            value: "Goodbye World!"
          - name: goodbye
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: goodbye-pod
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: goodbye-node
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: image
            value: "paulbouwer/hello-kubernetes:1.10"
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
